#!/bin/bash

##########################################################################
# author: hua.fang
# date: 2016/6/16
# function: describe register
##########################################################################

##################################   Register Format
# format:
#   === REG_NAME(reg_addr) ===
#	bit_name offset [len] [detail]
#	bit_name offset [len] [detail]
#
# explaination:
#   'REG_NAME' must be upper case, 'reg_addr' must be lower case
#   separate by space, so could not have space between each info
#
#   there are 3 types now, the parser would detect it automatically by parameters.
#	switch: 'len' & 'detail' must be null
#         array count must be 2
#         eg. ADC_EB 0
#	enum: detail is "<info of 0> <info of 1> ..."
#         array count must be larger than 5.
#         eg. PD_CA7_C1_STATE 8 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
#	value: detail is "<start value> <step value>", 'start' & 'step' can not be fractional digit
#         array count must be 5, 'len' is more than 1.
#         eg. PD_CA7_C0_STATE 4 4 0 1
#   # - comment

function list_regs() {
cat << EOF
####################################  module enable
=== AHB_EB(0x20e00000) ===
ZIPMTX_EB 23
LVDS_EB 22
ZIPDEC_EB 21
ZIPENC_EB 20
NANDC_ECC_EB 19
NANDC_2X_EB 18
NANDC_EB 17
BUSMON2_EB 16
BUSMON1_EB 15
BUSMON0_EB 14
SPINLOCK_EB 13
EMMC_EB 11
SDIO2_EB 10
SDIO1_EB 9
SDIO0_EB 8
DRM_EB 7
NFC_EB 6
DMA_EB 5
OTG_EB 4
GSP_EB 3
HSIC_EB 2
DISPC_EB 1
DSI_EB 0

=== APB_EB(0x71300000) ===
INTC3_EB 22
INTC2_EB 21
INTC1_EB 20
INTC0_EB 19
CKG_EB 18
UART4_EB 17
UART3_EB 16
UART2_EB 15
UART1_EB 14
UART0_EB 13
I2C4_EB 12
I2C3_EB 11
I2C2_EB 10
I2C1_EB 9
I2C0_EB 8
SPI2_EB 7
SPI1_EB 6
SPI0_EB 5
IIS3_EB 4
IIS2_EB 3
IIS1_EB 2
IIS0_EB 1
SIM0_EB 0

=== AON_APB_EB0(0x402e0000) ===
I2C_EB 31
CA7_DAP_EB 30
CA7_TS1_EB 29
CA7_TS0_EB 28
GPU_EB 27
CKG_EB 26
MM_EB 25
AP_WDG_EB 24
MSPI_EB 23
SPLK_EB 22
IPI_EB 21
PIN_EB 20
VBC_EB 19
AUD_EB 18
AUDIF_EB 17
ADI_EB 16
INTC_EB 15
EIC_EB 14
EFUSE_EB 13
AP_TMR0_EB 12
AON_TMR_EB 11
AP_SYST_EB 10
AON_SYST_EB 9
KPD_EB 8
PWM3_EB 7
PWM2_EB 6
PWM1_EB 5
PWM0_EB 4
GPIO_EB 3
TPC_EB 2
FM_EB 1
ADC_EB 0

=== AON_APB_EB1(0x402e0004) ===
ORP_JTAG_EB 27
CA5_TS0_EB 26
DEF_EB 25
LVDS_PLL_DIV_EN 24
ARM7_JTAG_EB 23
AON_DMA_EB 22
MBOX_EB 21
DJTAG_EB 20
RTC4M1_CAL_EB 19
RTC4M0_CAL_EB 18
MDAR_EB 17
LVDS_TCXO_EB 16
LVDS_TRX_EB 15
CA5_DAP_EB 14
GSP_EMC_EB 13
ZIP_EMC_EB 12
DISP_EMC_EB 11
AP_TMR2_EB 10
AP_TMR1_EB 9
CA7_WDG_EB 8
AVS_EB 6
PROBE_EB 5
AUX2_EB 4
AUX1_EB 3
AUX0_EB 2
THM_EB 1
PMU_EB 0

####################################  power state
=== PWR_STATUS0_DBG(0x402b00bc) ===
PD_MM_TOP_STATE 28 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_GPU_TOP_STATE 24 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_AP_SYS_STATE 20 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CA7_C3_STATE 16 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CA7_C2_STATE 12 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CA7_C1_STATE 8 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CA7_C0_STATE 4 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CA7_TOP_STATE 0 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC

=== PWR_STATUS1_DBG(0x402b00c0) ===
PD_CP0_CEVA_1_STATE 28 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP0_CEVA_0_STATE 24 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP0_GSM_0_STATE 20 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP0_GSM_1_STATE 16 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP0_HU3GE_STATE 12 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP0_ARM9_1_STATE 8 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP0_ARM9_0_STATE 4 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP0_TD_STATE 0 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC

=== PWR_STATUS2_DBG(0x402b00c4) ===
PD_PUB_SYS_STATE 24 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP1_COMWRAP_STATE 20 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP1_LTE_P2_STATE 16 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP1_LTE_P1_STATE 12 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP1_CEVA_STATE 8 4 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC
PD_CP1_CA5_STATE 4 0 WAKEUP POWER_ON_SEQ POWER_ON RST_ASSERT RST_GAP RESTORE ISO_OFF SHUTDOWN ACTIVE STANDBY ISO_ON SAVE_ST SAVE_GAP POWER_OFF BISR_RST BISR_PROC

=== SLEEP_CTRL(0x402b00cc) ===
VCP1_FORCE_LIGHT_SLEEP 28
VCP0_FORCE_LIGHT_SLEEP 27
CP1_FORCE_LIGHT_SLEEP 26
CP0_FORCE_LIGHT_SLEEP 25
AP_FORCE_LIGHT_SLEEP 24
ARM7_FORCE_DEEP_SLEEP 21
VCP1_FORCE_DEEP_SLEEP 20
VCP0_FORCE_DEEP_SLEEP 19
CP1_FORCE_DEEP_SLEEP 18
CP0_FORCE_DEEP_SLEEP 17
AP_FORCE_DEEP_SLEEP 16
VCP1_LIGHT_SLEEP 12
VCP0_LIGHT_SLEEP 11
CP1_LIGHT_SLEEP 10
CP0_LIGHT_SLEEP 9
AP_LIGHT_SLEEP 8
VCP1_DEEP_SLEEP 4
VCP0_DEEP_SLEEP 3
CP1_DEEP_SLEEP 2
CP0_DEEP_SLEEP 1
AP_DEEP_SLEEP 0

=== SLEEP_STATUS(0x402b00d4) ===
ARM7_SLP_STATUS 20 4 DEEP_SLEEP XTL_WAIT XTLBUF_WAIT DEEP_SLEEP_XTLON PLL_PWR_WAIT WAKEUP WAKEUP_LOCK NULL NULL NULL NULL NULL NULL NULL NULL NULL
VCP1_SLP_STATUS 16 4 DEEP_SLEEP XTL_WAIT XTLBUF_WAIT DEEP_SLEEP_XTLON PLL_PWR_WAIT WAKEUP WAKEUP_LOCK NULL NULL NULL NULL NULL NULL NULL NULL NULL
VCP0_SLP_STATUS 12 4 DEEP_SLEEP XTL_WAIT XTLBUF_WAIT DEEP_SLEEP_XTLON PLL_PWR_WAIT WAKEUP WAKEUP_LOCK NULL NULL NULL NULL NULL NULL NULL NULL NULL
CP1_SLP_STATUS 8 4 DEEP_SLEEP XTL_WAIT XTLBUF_WAIT DEEP_SLEEP_XTLON PLL_PWR_WAIT WAKEUP WAKEUP_LOCK NULL NULL NULL NULL NULL NULL NULL NULL NULL
CP0_SLP_STATUS 4 4 DEEP_SLEEP XTL_WAIT XTLBUF_WAIT DEEP_SLEEP_XTLON PLL_PWR_WAIT WAKEUP WAKEUP_LOCK NULL NULL NULL NULL NULL NULL NULL NULL NULL
AP_SLP_STATUS 0 4 DEEP_SLEEP XTL_WAIT XTLBUF_WAIT DEEP_SLEEP_XTLON PLL_PWR_WAIT WAKEUP WAKEUP_LOCK NULL NULL NULL NULL NULL NULL NULL NULL NULL

=== CP_SLP_STATUS_DBG0(0x402b00b4) ===
tmr_autopd_xtl_2g 15
tmr_autopd_xtl_3g_w 14
clk_ecc_en 13
clk_qbc_en 12
dsp_stop 11
wsys_stop 10
dsp_peri_stop 9
mcu_peri_stop 8
mcu_sys_stop 7
mcu_deep_stop 6
dsp_mahb_sleep_en 5
ashb_dsptoarm_valid 4
mcu_stop 3
ahb_stop 2
mtx_stop 1
arm_stop 0

####################################  configuration
=== XTL0_REL_CFG(0x402b0080) ===
XTL0_ARM7_SEL 5
XTL0_VCP1_SEL 4
XTL0_VCP0_SEL 3
XTL0_CP1_SEL 2
XTL0_CP0_SEL 1
XTL0_AP_SEL 0

=== XTL1_REL_CFG(0x402b0084) ===
XTL1_ARM7_SEL 5
XTL1_VCP1_SEL 4
XTL1_VCP0_SEL 3
XTL1_CP1_SEL 2
XTL1_CP0_SEL 1
XTL1_AP_SEL 0

=== XTLBUF0_REL_CFG(0x402b008c) ===
XTLBUF0_ARM7_SEL 5
XTLBUF0_VCP1_SEL 4
XTLBUF0_VCP0_SEL 3
XTLBUF0_CP1_SEL 2
XTLBUF0_CP0_SEL 1
XTLBUF0_AP_SEL 0

=== XTLBUF1_REL_CFG(0x402b0090) ===
XTLBUF1_ARM7_SEL 5
XTLBUF1_VCP1_SEL 4
XTLBUF1_VCP0_SEL 3
XTLBUF1_CP1_SEL 2
XTLBUF1_CP0_SEL 1
XTLBUF1_AP_SEL 0

=== MPLL_REL_CFG(0x402b0094) ===
MPLL_REF_SEL 8
MPLL_ARM7_SEL 5
MPLL_VCP1_SEL 4
MPLL_VCP0_SEL 3
MPLL_CP1_SEL 2
MPLL_CP0_SEL 1
MPLL_AP_SEL 0

=== DPLL_REL_CFG(0x402b0098) ===
DPLL_REF_SEL 8
DPLL_ARM7_SEL 5
DPLL_VCP1_SEL 4
DPLL_VCP0_SEL 3
DPLL_CP1_SEL 2
DPLL_CP0_SEL 1
DPLL_AP_SEL 0

=== LTEPLL_REL_CFG(0x402b009c) ===
LTEPLL_REF_SEL 8
LTEPLL_ARM7_SEL 5
LTEPLL_VCP1_SEL 4
LTEPLL_VCP0_SEL 3
LTEPLL_CP1_SEL 2
LTEPLL_CP0_SEL 1
LTEPLL_AP_SEL 0

=== TWPLL_REL_CFG(0x402b00a0) ===
TWPLL_REF_SEL 8
TWPLL_ARM7_SEL 5
TWPLL_VCP1_SEL 4
TWPLL_VCP0_SEL 3
TWPLL_CP1_SEL 2
TWPLL_CP0_SEL 1
TWPLL_AP_SEL 0

=== LVDSDIS_PLL_REL_CFG(0x402b00a4) ===
LVDSDIS_PLL_REF_SEL 8
LVDSDIS_PLL_ARM7_SEL 5
LVDSDIS_PLL_VCP1_SEL 4
LVDSDIS_PLL_VCP0_SEL 3
LVDSDIS_PLL_CP1_SEL 2
LVDSDIS_PLL_CP0_SEL 1
LVDSDIS_PLL_AP_SEL 0

####################################  ldo configuration
=== ANA_REG_GLB_LDO_DCDC_PD(0x40038810) ===
LDO_EMM_PD 15
DCDC_TOPCLK6M_PD 14
DCDC_RF_PD 13
DCDC_GEN_PD 12
DCDC_MEM_PD 11
DCDC_ARM_PD 10
DCDC_CORE_PD 9
LDO_RF0_PD 8
LDO_EMMCCORE_PD 7
LDO_GEN1_PD 6
LDO_DCXO_PD 5
LDO_GEN0_PD 4
LDO_VDD25_PD 3
LDO_VDD28_PD 2
LDO_VDD18_PD 1
BG_PD 0

=== ANA_REG_GLB_LDO_PD_CTRL(0x40038814) ===
LDO_LPREF_PD_SW 15
DCDC_WPA_PD 14
DCDC_CON_PD 13
LDO_WIFIPA_PD 11
LDO_SDCORE_PD 10
LDO_USB_PD 8
LDO_CAMMOT_PD 7
LDO_CAMIO_PD 6
LDO_CAMD_PD 5
LDO_CAMA_PD 4
LDO_SIM2_PD 3
LDO_SIM1_PD 2
LDO_SIM0_PD 1
LDO_SDIO_PD 0

=== ANA_REG_GLB_PWR_SLP_CTRL0(0x40038890) ===
SLP_IO_EN 15
SLP_DCDCRF_PD_EN 13
SLP_DCDCCON_PD_EN 12
SLP_DCDCGEN_PD_EN 11
SLP_DCDCWPA_PD_EN 10
SLP_DCDCARM_PD_EN 9
SLP_LDOVDD25_PD_EN 8
SLP_LDORF0_PD_EN 7
SLP_LDOEMMCCORE_PD_EN 6
SLP_LDOGEN0_PD_EN 5
SLP_LDODCXO_PD_EN 4
SLP_LDOGEN1_PD_EN 3
SLP_LDOWIFIPA_PD_EN 2
SLP_LDOVDD28_PD_EN 1
SLP_LDOVDD18_PD_EN 0

=== ANA_REG_GLB_PWR_SLP_CTRL1(0x40038894) ===
SLP_LDO_PD_EN 15
SLP_LDOLPREF_PD_EN 14
SLP_LDOSDCORE_PD_EN 9
SLP_LDOUSB_PD_EN 8
SLP_LDOCAMMOT_PD_EN 7
SLP_LDOCAMIO_PD_EN 6
SLP_LDOCAMD_PD_EN 5
SLP_LDOCAMA_PD_EN 4
SLP_LDOSIM2_PD_EN 3
SLP_LDOSIM1_PD_EN 2
SLP_LDOSIM0_PD_EN 1
SLP_LDOSDIO_PD_EN 0

=== ANA_REG_GLB_PWR_SLP_CTRL2(0x40038898) ===
SLP_DCDCRF_LP_EN 14
SLP_DCDCCON_LP_EN 13
SLP_DCDCCORE_LP_EN 12
SLP_DCDCMEM_LP_EN 11
SLP_DCDCARM_LP_EN 10
SLP_DCDCGEN_LP_EN 9
SLP_DCDCWPA_LP_EN 8
SLP_LDORF0_LP_EN 7
SLP_LDOEMMCCORE_LP_EN 6
SLP_LDOGEN0_LP_EN 5
SLP_LDODCXO_LP_EN 4
SLP_LDOGEN1_LP_EN 3
SLP_LDOWIFIPA_LP_EN 2
SLP_LDOVDD28_LP_EN 1
SLP_LDOVDD18_LP_EN 0

=== ANA_REG_GLB_PWR_SLP_CTRL3(0x4003889c) ===
SLP_BG_LP_EN 15
LDOVDD25_LP_EN_SW 14
LDOSDCORE_LP_EN_SW 13
LDOUSB_LP_EN_SW 12
SLP_LDOVDD25_LP_EN 10
SLP_LDOSDCORE_LP_EN 9
SLP_LDOUSB_LP_EN 8
SLP_LDOCAMMOT_LP_EN 7
SLP_LDOCAMIO_LP_EN 6
SLP_LDOCAMD_LP_EN 5
SLP_LDOCAMA_LP_EN 4
SLP_LDOSIM2_LP_EN 3
SLP_LDOSIM1_LP_EN 2
SLP_LDOSIM0_LP_EN 1
SLP_LDOSDIO_LP_EN 0

=== ANA_REG_GLB_PWR_SLP_CTRL4(0x400388a0) ===
LDOCAMIO_LP_EN_SW 15
LDOCAMMOT_LP_EN_SW 14
LDOCAMD_LP_EN_SW 13
LDOCAMA_LP_EN_SW 12
LDOSIM2_LP_EN_SW 11
LDOSIM1_LP_EN_SW 10
LDOSIM0_LP_EN_SW 9
LDOSDIO_LP_EN_SW 8
LDORF0_LP_EN_SW 7
LDOEMMCCORE_LP_EN_SW 6
LDOGEN0_LP_EN_SW 5
LDODCXO_LP_EN_SW 4
LDOGEN1_LP_EN_SW 3
LDOWIFIPA_LP_EN_SW 2
LDOVDD28_LP_EN_SW 1
LDOVDD18_LP_EN_SW 0

=== ANA_REG_GLB_PWR_XTL_EN0(0x400388c4) ===
LDO_XTL_EN 15
LDO_GEN0_EXT_XTL0_EN 14
LDO_GEN0_XTL1_EN 13
LDO_GEN0_XTL0_EN 12
LDO_GEN1_EXT_XTL0_EN 11
LDO_GEN1_XTL1_EN 10
LDO_GEN1_XTL0_EN 9
LDO_DCXO_EXT_XTL0_EN 8
LDO_DCXO_XTL1_EN 7
LDO_DCXO_XTL0_EN 6
LDO_VDD18_EXT_XTL0_EN 5
LDO_VDD18_XTL1_EN 4
LDO_VDD18_XTL0_EN 3
LDO_VDD28_EXT_XTL0_EN 2
LDO_VDD28_XTL1_EN 1
LDO_VDD28_XTL0_EN 0

=== ANA_REG_GLB_PWR_XTL_EN0(0x400388c8) ===
LDO_RF0_EXT_XTL0_EN 14
LDO_RF0_XTL1_EN 13
LDO_RF0_XTL0_EN 12
LDO_WIFIPA_EXT_XTL0_EN 11
LDO_WIFIPA_XTL1_EN 10
LDO_WIFIPA_XTL0_EN 9
LDO_SIM2_EXT_XTL0_EN 8
LDO_SIM2_XTL1_EN 7
LDO_SIM2_XTL0_EN 6
LDO_SIM1_EXT_XTL0_EN 5
LDO_SIM1_XTL1_EN 4
LDO_SIM1_XTL0_EN 3
LDO_SIM0_EXT_XTL0_EN 2
LDO_SIM0_XTL1_EN 1
LDO_SIM0_XTL0_EN 0

=== ANA_REG_GLB_PWR_XTL_EN0(0x400388cc) ===
LDO_VDD25_EXT_XTL0_EN 11
LDO_VDD25_XTL1_EN 10
LDO_VDD25_XTL0_EN 9
DCDC_RF_EXT_XTL0_EN 8
DCDC_RF_XTL1_EN 7
DCDC_RF_XTL0_EN 6
XO_EXT_XTL0_EN 5
XO_XTL1_EN 4
XO_XTL0_EN 3
BG_EXT_XTL0_EN 2
BG_XTL1_EN 1
BG_XTL0_EN 0

=== ANA_REG_GLB_PWR_XTL_EN0(0x400388d0) ===
DCDC_CON_EXT_XTL0_EN 14
DCDC_CON_XTL1_EN 13
DCDC_CON_XTL0_EN 12
DCDC_WPA_EXT_XTL0_EN 11
DCDC_WPA_XTL1_EN 10
DCDC_WPA_XTL0_EN 9
DCDC_MEM_EXT_XTL0_EN 8
DCDC_MEM_XTL1_EN 7
DCDC_MEM_XTL0_EN 6
DCDC_GEN_EXT_XTL0_EN 5
DCDC_GEN_XTL1_EN 4
DCDC_GEN_XTL0_EN 3
DCDC_CORE_EXT_XTL0_EN 2
DCDC_CORE_XTL1_EN 1
DCDC_CORE_XTL0_EN 0
EOF
}

